<?php

/**
 * Implements hook_libraries_info().
 *
 * @see hook_libraries_info()
 */
function globalcarboncities_libraries_info() {
  $libraries['globalcarboncities'] = array(
    'name' => 'globalcarboncities',
    'vendor url' => '',
    'download url' => '',
    'version callback' => 'globalcarboncities_version_callback',
    'files' => array(
      'js' => array(
        #'lib/bootstrap.min.js',
        'lib/d3.v4.min.js',
        'lib/i18next.min.js',
        'lib/queue.v1.min.js',
        'lib/stc_visualization_components/utils.min.js',
        'lib/stc_visualization_components/bar.min.js',
        'lib/d3-tip.js',
        'lib/d3-array.v1.min.js',
        'lib/d3-geo.v1.min.js',
        'lib/d3-geo-projection.v2.min.js',
        'lib/topojson.v1.min.js',
        'lib/jquery.class.js',
        'lib/Help.js',
        'src/index.js',
      ),
      'css' => array(
        'lib/bootstrap.min.css',
        'src/globalcarboncities.css',
      ),
    ),
  );

  return $libraries;
}

function globalcarboncities_version_callback() {
  return TRUE;
}

/**
 * Implements hook_menu().
 */
function globalcarboncities_menu() {
  $items['global-carbon-cities'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('A global dataset of CO2 emissions and related ancillary data'),
    'description' => '',
    'page callback' => 'globalcarboncities_page',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Page callback.
 */
function globalcarboncities_page() {
  drupal_add_js(array('dv' => array('urlRoot' => libraries_get_path('globalcarboncities'))), 'setting');
  $content = array(
    'intro' => array(
      '#type' => 'markup',
      '#markup' => '<div class="container" id="thisContainer" style="width:1200px;">

        <!-- divs for help overlay -->
        <div id="helpTitleName"></div>
        <div id="helpCardName"></div>
        <div id="helpMenuName"></div>
        <div id="helpUnitsName"></div>
        <div id="helpBarsName"></div>
        <div id="helpBarHoverName"></div>

        <!-- header row -->
        <div class="row">
          <div class="col-md-3" id="download"></div>
          <div class="col-lg-6 headings" id="pageTitle">A global dataset of CO2 emissions and related ancillary data</div>
          <div class="col-lg-1">
            <ul class="navbar-header">
              <button id="mapResetButton" class="btn btn-info" type="button">Clear</button>
            </ul>
          </div>
          <div class="col-lg-1">
            <ul class="navbar-header">
              <button id="helpButton" class="btn btn-info" type="button">Help</button>
            </ul>
          </div>


        </div> <!-- ./header row -->


        <!-- 2nd row -->
        <div class="row">
          <div class="col-lg-3" id="mycityCardDiv"> </div>
          <div class="col-lg-9" id="map"> </div>
        </div>

         <!-- Link to data and paper row -->
        <div class="row">
          <div class="col-lg-10" style="text-align: left; font-weight:normal; left: 0px;"></div>
        </div>



        <!-- row for barChart title and toggle buttons -->
        <div class="row">
          <div id="barChartCaption" class="col-lg-4 headings">Per capita emissions</div>
          <div class="col-lg-2" id="selector">
            <label for="attrSelector">Colour bars by</label>
          </div>
          <div class="col-lg-2">
            <select id="dropdownMenu" class="form-control">
              <option value="region" selected="selected">Region</option>
                <option value="protocol">Protocol</option>
                <option value="year">Measurement year</option>
                <option value="population">Population</option>
                <option value="GDP_PPP_percap">GDP-PPP/cap</option>
                <option value="area">Area</option>
                <option value="pop_density">Population density</option>
                <option value="diesel">Diesel price</option>
                <option value="gas">Gas price</option>
                <option value="HDD">HDD 15.5C</option>
                <option value="CDD">CDD 23C</option>
                <option value="low_bua_pc_2014">Low BUA (2014)</option>
                <option value="high_bua_pc_2014">High BUA (2014)</option>
                <option value="none">None</option>
            </select>

          </div>
          <div class="col-lg-2">
            <div id="barChartLegend">
               <svg></svg>
            </div>
          </div>
          <div class="col-lg-2 units"></div>
        </div> <!-- .end row -->

        <!-- ****************************************** -->
        <!-- BAR CHARTS -->
        <!-- ****************************************** -->

        <!-- BarChart ROW1: groupEastAsia -->
        <div class="row">
          <!-- <div id="barChartCaption" class="headings">Per capita emissions [tCO₂eq/capita]</div> -->
          <div id="h1" class="col-lg-2 headingClass"></div>
          <div class="col-lg-12">
            <div class="data EAdata"></div>
          </div>
        </div>

        <!-- BarChart ROW2: groupNAmer -->
        <div class="row">
          <div id="h2" class="col-lg-2 headingClass"></div>
          <div class="col-lg-12">
            <div class="data NAdata"></div>
          </div>
        </div>

        <!-- BarChart ROW3: groupEurope and groupSEAsia -->
        <div class="row">
          <div id="h3" class="col-lg-8 headingClass"></div>
          <div id="h4" class="col-lg-4 headingClass"></div>
          <div class="col-lg-12">
            <div class="data EUdata"></div>
          </div>
        </div>

        <!-- BarChart ROW4: groupLatinAmer, groupSEAsia, groupSAsia -->
         <div class="row">
          <div class="col-lg-12">
            <div id="h5" class="col-lg-3 headingClass"></div>
            <div id="h6" class="col-lg-2 headingClass"></div>
            <div id="h7" class="col-lg-3 headingClass"></div>
            <div id="h8" class="col-lg-2 headingClass"></div>
            <div id="h9" class="col-lg-2 headingClass"></div>
            <div class="data dataRow4"></div>
          </div>
        </div>

        <footer class="row">
          <div class="col-lg-2 footerClass" id="logo_BNP">
            <a target="_blank" href="https://group.bnpparibas/en/group/bnp-paribas-foundation"><img src="' . libraries_get_path('globalcarboncities') . '/img/BNPParisbasFoundation.jpg" title="BNP Parisbas Foundation" width="75" height="75"/></a>
          </div>

          <div class="col-lg-2 footerClass" id="logo_GCP"> <!-- ratio 1:2.3 -->
            <a target="_blank" href="http://www.globalcarbonproject.org/"><img src="' . libraries_get_path('globalcarboncities') . '/img/GCP.png" title="GCP" width="117" height="50"/></a>
          </div>

          <div class="col-lg-2 footerClass" id="logo_CDP"> <!-- ratio 1:2.8 -->
            <a target="_blank" href="https://www.cdp.net/en"><img src="' . libraries_get_path('globalcarboncities') . '/img/CDP.png" title="CDP" width="114" height="40"/></a>
          </div>

        </footer>
      </div>',
      '#attached' => array(
        'libraries_load' => array(array('globalcarboncities')),
      )
    )
  );

  return $content;
}
